### ISSUE TITLE
Progress of RISC-V SBI calling convention maps to the ARM PSCI calling convention

### ISSUE THREAD

**Issue by gagachang** [riscv-non-isa/riscv-sbi-doc#111]
I found the following slides shows the compaison between SBI and ARM PSCI:
https://lists.riscv.org/g/tech-unixplatformspec/topic/risc_v_sbi_vs_arm_psci/77906648

And there is a topic:
```
How the RISC-V SBI calling convention maps to the ARM PSCI calling convention (and vice-versa)
```

Further more, [ARM SMCCC](https://developer.arm.com/documentation/den0028/latest/) has four registers `W0 ~ W3` used to be return values, althought SBI only has `a0 and a1`.

Is there any progress or materials to standarize this topic?

**Comment by atishp04** [comment]
There is no plan to make any changes to return arguments and extend it more registers similar to PSCI. The slides reference above was presented to indicate that we can't reuse most of the PSCI spec for the reasons describe there.

**Comment by atishp04** [comment]
Can we close this ? @gagachang

**Comment by gagachang** [comment]
Sure, I am closing it.
