### ISSUE TITLE
Is there any spec to support Sdtrig extension?

### ISSUE THREAD

**Issue by cyyself** [riscv-non-isa/riscv-sbi-doc#139]
Since debug triggers defined in the Sdtrig extension can only be accessed by Debug Mode and M-mode, I think an SBI extension is needed to support debug control from S-Mode software.

**Comment by atishp04** [comment]
Yes. The SBI extension is already proposed here.
https://lists.riscv.org/g/tech-debug/topic/99825362#1302

**Comment by atishp04** [comment]
closing the issue now. Please reopen if you need more details.
