### ISSUE TITLE
Unclear return type in Chapter 9.3: Hart Get Status

### ISSUE THREAD

**Issue by sfiedler0** [riscv-non-isa/riscv-sbi-doc#168]
As I am currently trying to write an OS for RISC-V in Zig (earlier x86_64, but after I got stuck with paging I stopped that), I found the SBI and am currently implementing it. I chose the release candidate for 3.0 to find possible mistakes.

In chapter 9.3 (Hart Get Status), there is "Get the current status (or HSM state id) of the given hart in `sbiret.value`, or an error through `sbiret.error`".  
This sentence does not give any information on when the return value should be used and when the error should be used. Currently I implemented it like "if the error is success, return the value, else return the error", but as nothing specific is written there, I think this should change.

**Comment by atishp04** [comment]
closing this issue as the patch is merged
