### ISSUE TITLE
SBI Spec Version (chapter 4.1) is only defined for 32 bits

### ISSUE THREAD

**Issue by sfiedler0** [riscv-non-isa/riscv-sbi-doc#170]
In chapter 4.1 (Get SBI specification version) the version is described as "minor number in low 24 bits, major number in next 7 bits, bit 31 is 0". By doing this, we only get 32 bits. What about RISC-V 64 where the return value is 8 bytes (64 bits) wide?  
I already implemented it for me by just truncating it (ignoring the high 32 bits), but I think this could be in the specification.

**Comment by SiFiveHolland** [comment]
The upper 32 bits would also be reserved. I submitted a patch to clarify this:

https://lists.riscv.org/g/tech-prs/topic/patch_specify_high_bits_of/108873237
