### ISSUE TITLE
Spelling Errors

### ISSUE THREAD

**Issue by sfiedler0** [riscv-non-isa/riscv-sbi-doc#171]
While implementing this spec (3.0-rc1) in Zig, I found a spelling error: in Chapter 17.8 (<https://github.com/riscv-non-isa/riscv-sbi-doc/blob/master/src/ext-sse.adoc?plain=1#L386>) there is written "paramter" instead of "parameter". 

Now a question: how do we address spelling errors here?  
I found only one spelling error, but they happen from time to time.

**Comment by avpatel** [comment]
For trivial typos, spelling errors, or grammar you can raise a GitHub PR.

Functional or behaviour changes need more discussion on PRS mailing list and PRS meetings.
