### ISSUE TITLE
The in Chapter 20.7 and 20.8 mentioned parameter "base_attribute_count_id" does not exist in the function signature

### ISSUE THREAD

**Issue by sfiedler0** [riscv-non-isa/riscv-sbi-doc#176]
Probably the "base_attribute_id" parameter was meant, but since I am not the author of this extension, I don't know.

**Comment by pathakraul** [comment]
Yes, I can confirm that **base_attribute_count_id** is a typo. It must be **base_attribute_id**. If you want, you can raise the PR? 

Thanks for finding the recent issues

**Comment by sfiedler0** [comment]
Yes, I'll do that.
