### ISSUE TITLE
FWFT: reference attribute table or attribute-values table

### ISSUE THREAD

**Issue by jones-drew** [riscv-non-isa/riscv-sbi-doc#183]
Both the "Firmware Features Set" and the "Firmware Features Get" sections have "...values are described in <table>..." text, where <table> is the "FWFT Feature Attributes" table. On one hand, that's fine, since that table describes how to interpret "FWFT Feature Attribute Values", but on the other hand "values are described in..." implies that the table should describe values instead of attributes. I'd prefer we change the referenced table from the attribute table to the attribute-values table.

**Comment by atishp04** [comment]
Agreed.
https://github.com/riscv-non-isa/riscv-sbi-doc/pull/185
