### ISSUE TITLE
Make latest release available at RISC-V Website as PDF

### ISSUE THREAD

**Issue by axel-h** [riscv-non-isa/riscv-sbi-doc#70]
The RISC-V website's spec section at https://riscv.org/technical/specifications does not say anything about the SBI at the moment. The latest release should be made available there as PDF document together with a link to this repo and the latest master draft https://github.com/riscv/riscv-sbi-doc/blob/master/riscv-sbi.adoc. OpenSBI as reference implementation should also be linked there.

**Comment by atishp04** [comment]
Good suggestion.  I will check with Stephano on the process to do that.

**Comment by atishp04** [comment]
I have followed up with Stephano/Jeff few times. It seems the specification page is not actively maintained. I will follow up with them again about referencing the SBI spec if there is any renewed interest.
