### ISSUE TITLE
Update to RISC-V Template

### ISSUE THREAD

**Issue by jjscheel** [riscv-non-isa/riscv-sbi-doc#84]
Need to update the same look and feel as the other RISC-V document.  This is accomplished by the following steps: 

1. Utilize GitHub submodules to include a docs-resources project.
2. Updates to the README document to explain how to clone with submodules
3. Creation of an image/ directory with a riscv-images symlink into the docs-resources
4. Updates to the Makefile to use the RISC-V fonts and themes when building
5. Removal of the old theme file (riscv-sbi-theme.yaml).
6. Addition of necessary Asciidoctor variables to the main adoc file (riscv-sbi.adoc).
7. Updating the document level to 1.0-rc2 and adding change log entry (riscv-sbi.adoc)

**Comment by atishp04** [comment]
Merged in PR #89. Closing the issue
